const actionsTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    OPEN_SELECTED_PRODUCT_PAGE: 'OPEN_SELECTED_PRODUCT_PAGE',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
    RETRIEVE_CART: 'RETRIEVE_CART',
    SET_CHECKOUTTOKEN: 'SET_CHECKOUTTOKEN'
}

export default actionsTypes